services:
  # PostgreSQL Service
  postgres:
    image: postgres:alpine3.23
    hostname: postgres
    container_name: postgres
    restart: alwayspsql -U myuser -d mydatabase
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'mydatabase'
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mydatabase']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  # Next.js Application and Prisma Studio Service
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      DATABASE_URL: 'postgresql://myuser:mypassword@postgres:5432/mydatabase?schema=public'
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - ./next-app/prisma:/app/prisma
    ports:
      - '3000:3000' # Next.js
      - '5555:5555' # Prisma studio
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - prisma-network
    # command: >
    #   sh -c "npm run dev & npx prisma studio --port 5555 --browser none"
    # stdin_open: true
    # tty: true # Keeps the container running for debugging

    # File synchronization and rebuild watch actions
    develop:
      watch:
        - action: sync
          path: ./next-app/src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: sync
          path: ./next-app/public
          target: /app/public
          ignore:
            - node_modules/
        - action: rebuild
          path: ./next-app/package.json
          target: /app/package.json
        - action: rebuild
          path: ./next-app/pnpm-lock.yaml
          target: /app/pnpm-lock.yaml
        - action: rebuild
          path: ./next-app/package-lock.json
          target: /app/package-lock.json
        - action: sync+restart
          path: ./next-app/next.config.ts
          target: /app/next.config.ts
        - action: sync+restart
          path: ./next-app/tsconfig.json
          target: /app/tsconfig.json
        - action: sync+restart
          path: ./next-app/postcss.config.mjs
          target: /app/postcss.config.mjs

networks:
  prisma-network:
    driver: bridge
    name: caliber_prisma-network

volumes:
  postgres_data:
