[project]
name = "caliber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "curl-cffi>=0.13.0",
    "fastapi==0.115.0",
    "httpx>=0.28.1",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "pdfplumber==0.11.4",
    "pydantic>=2.9.2",
    "pytest==8.3.3",
    "python-dotenv>=1.2.1",
    "python-multipart==0.0.9",
    "requests>=2.32.5",
    "selenium>=4.38.0",
    "uvicorn==0.30.6",
    "webdriver-manager>=4.0.2",
]
